# Spring Boot
spring.application.name=todo

# ???? ??????
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA ?????????
spring.jpa.hibernate.ddl-auto=validate 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ???????????
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG